### ISSUE TITLE
Additional Features to be Implemented

### ISSUE THREAD

**Issue by shyammk** [universalturtles/Lisibilite#1]
As we know, there are several software products in the market that calculates readability scores. As such, we need to come up with a set of additional features that would help the users.

If you have any additional features in mind, let us discuss the same here. This could be visualizations, new metrics, word clouds etc.

Any ideas, shoot!

**Comment by ats0stv** [comment]
Some of the ideas in mind
- Word Counts with an ability to filter out articles, titles, figures, tables, references etc., (Academic)
- Ability to create readability reports with custom title and sections
*Some sections in the report can be* 
    - Lisibilite Readability Graph - Something in my mind
    - Word Density Analysis
    - Noun Phrase / Verb Phrase Composition Analysis
    - And one day - some day - Summary / Abstract of the text
    - Text Sentiment - someday - one day
    - Spelling Errors
- An API for programmatic access to our service (**No one has given it as such**)
    - Initially, it will be very much rate limited. We can see how we can extend it.
- One day, someday, we can start supporting other languages - **that will be yoyo**

**Comment by ats0stv** [comment]
@chhabriv and @rupdeb  
Please add your review comments, so that one round of review and we can close this issue.

**Comment by rupdeb** [comment]
It would be really useful if a brief summary/bullet points of the readability metrics that are intended to be responded with can be listed first. Additional/incremental features need to be introduced like any other intelligent service and @ats0stv has already laid out some of them. 

P.S: Do we need to provide a feature that checks whether the document is conforming to a particular format the user wants or not?

**Comment by shyammk** [comment]
I have an idea that is a little far stretched as of now. Since we are planning to launch this commercially in the longer run, I believe we must give the facility of user accounts. We must also categorize some of our features as "Premium", for which they will have to pay :P (Of course all these would be after we get enough user traffic). That would also give us scope for some user-specific analytics.
